version: '3.9'
services:
  nginx-service:
    restart: always
    image: nginx:stable-alpine
    container_name: nginx_apline_container
    ports:
      - 8443:8443
    volumes:
      - ~/data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/data/nginx/ucb_unet_ev_06_Oct_2021.key:/ucb_unet_ev_06_Oct_2021.key
      - ~/data/nginx/unet_ucb_com_bd_06_Oct_2021.cer:/unet_ucb_com_bd_06_Oct_2021.cer