version: '3'

services:
  ansible:
    build:
      context: ./ansible
    volumes:
        # Your Custome Volume Mappings Here
      - ~/Documents/projects:/home/ansible
      - ~/.ssh:/home/ansible/.ssh
      - ~/.gitconfig:/home/ansible/.gitconfig
    stdin_open: true
    tty: true
    command: tail -f /dev/null